# Generated by Django 3.2.9 on 2022-01-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addStd',
            fields=[
                ('stdId', models.IntegerField(primary_key=True, serialize=False)),
                ('stdName', models.CharField(max_length=25)),
                ('stdPassword', models.CharField(max_length=25)),
                ('stdEmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
