# Generated by Django 4.1 on 2022-08-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="addstd", old_name="stdEmail", new_name="stdFather",
        ),
    ]
