# Generated by Django 4.1 on 2022-08-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formApp", "0002_rename_stdemail_addstd_stdfather"),
    ]

    operations = [
        migrations.AddField(
            model_name="addstd", name="stdDOB", field=models.IntegerField(default=0),
        ),
    ]
