# Generated by Django 4.1 on 2022-08-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formApp", "0003_addstd_stddob"),
    ]

    operations = [
        migrations.RenameField(
            model_name="addstd", old_name="stdId", new_name="stdID",
        ),
        migrations.AlterField(
            model_name="addstd",
            name="stdDOB",
            field=models.DateField(blank=True, null=True),
        ),
    ]
