# Generated by Django 4.1 on 2022-08-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0004_rename_stdid_addstd_stdid_alter_addstd_stddob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addstd',
            name='stdPassword',
        ),
        migrations.AlterField(
            model_name='addstd',
            name='stdDOB',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='addstd',
            name='stdFather',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
