# Generated by Django 4.1 on 2022-08-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formApp", "0005_remove_addstd_stdpassword_alter_addstd_stddob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addstd",
            name="stdDOB",
            field=models.DateField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="addstd",
            name="stdFather",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
