# Generated by Django 4.1 on 2022-08-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formApp", "0006_alter_addstd_stddob_alter_addstd_stdfather"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addstd", name="stdDOB", field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="addstd",
            name="stdFather",
            field=models.EmailField(max_length=20),
        ),
    ]
