# Generated by Django 4.1 on 2022-08-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formApp", "0007_alter_addstd_stddob_alter_addstd_stdfather"),
    ]

    operations = [
        migrations.AddField(
            model_name="addstd",
            name="stdAddress",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="addstd",
            name="stdCNIC",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="addstd",
            name="stdCourse",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="addstd",
            name="stdEmail",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="addstd",
            name="stdEmergencyContactPerson",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="addstd",
            name="stdEmergencyContactPersonNumber",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="addstd",
            name="stdGender",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="addstd",
            name="stdMobile",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="addstd",
            name="stdPhoto",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="addstd",
            name="stdFather",
            field=models.CharField(max_length=20),
        ),
    ]
